/* ------------------------------------------------------------------ */
/*  Send the plan email with PDF attachment via Resend                 */
/* ------------------------------------------------------------------ */

import { Resend } from 'resend'
import type { DetailedPlan } from './generate-detailed-plan'

const SUBJECTS: Record<string, string> = {
  en: 'Your ALE Digital Transformation Plan',
  fr: 'Votre plan de transformation digitale ALE',
}

function buildHtmlBody(plan: DetailedPlan, email: string, locale: string): string {
  const isEn = locale !== 'fr'

  const greeting = isEn
    ? 'Thank you for exploring solutions with Alcatel-Lucent Enterprise.'
    : 'Merci d\u2019avoir exploit\u00e9 les solutions Alcatel-Lucent Enterprise.'

  const planReady = isEn
    ? 'Your personalized plan is ready!'
    : 'Votre plan personnalis\u00e9 est pr\u00eat\u00a0!'

  const ctaText = isEn ? 'Contact Sales' : 'Contacter les ventes'
  const footerText = isEn
    ? 'This plan was generated by the ALE Digital Advisor.'
    : 'Ce plan a \u00e9t\u00e9 g\u00e9n\u00e9r\u00e9 par ALE Digital Advisor.'

  const topProductLine =
    plan.topProduct
      ? `<p style="margin:8px 0;font-size:14px;color:#374151;"><strong>${isEn ? 'Top Recommendation' : 'Recommandation principale'}: </strong>${plan.topProduct}</p>`
      : ''

  return `<!DOCTYPE html>
<html lang="${locale}">
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#F3F4F6;font-family:Arial,Helvetica,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F3F4F6;padding:32px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#FFFFFF;border-radius:8px;overflow:hidden;">
        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,#6D28D9,#2563EB);padding:32px 40px;">
            <p style="margin:0;font-size:12px;color:rgba(255,255,255,0.8);text-transform:uppercase;letter-spacing:1px;">Alcatel-Lucent Enterprise</p>
            <h1 style="margin:8px 0 0;font-size:22px;color:#FFFFFF;">${planReady}</h1>
          </td>
        </tr>
        <!-- Body -->
        <tr>
          <td style="padding:32px 40px;">
            <p style="font-size:15px;color:#374151;line-height:1.6;">${greeting}</p>
            <div style="margin:20px 0;padding:16px;background:#F9FAFB;border-left:4px solid #7C3AED;border-radius:4px;">
              <p style="margin:0;font-size:14px;color:#1E3A5F;font-style:italic;">"${plan.executiveSummary.slice(0, 300)}${plan.executiveSummary.length > 300 ? '...' : ''}"</p>
            </div>
            ${topProductLine}
            <p style="font-size:14px;color:#374151;line-height:1.6;">
              ${isEn ? 'Please find your detailed plan attached as a PDF.' : 'Veuillez trouver votre plan d\u00e9taill\u00e9 en pi\u00e8ce jointe au format PDF.'}
            </p>
            <!-- CTA -->
            <table cellpadding="0" cellspacing="0" style="margin:24px 0;">
              <tr>
                <td style="background:#6D28D9;border-radius:6px;padding:12px 28px;">
                  <a href="https://www.al-enterprise.com/contact" style="color:#FFFFFF;text-decoration:none;font-size:14px;font-weight:bold;">${ctaText}</a>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <!-- Footer -->
        <tr>
          <td style="padding:20px 40px;background:#F9FAFB;border-top:1px solid #E5E7EB;">
            <p style="margin:0;font-size:12px;color:#9CA3AF;">${footerText}</p>
            <p style="margin:4px 0 0;font-size:12px;color:#9CA3AF;">al-enterprise.com</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`
}

export async function sendPlanEmail(
  email: string,
  plan: DetailedPlan,
  pdfBytes: Uint8Array,
  locale: string,
): Promise<{ id: string }> {
  const apiKey = process.env.RESEND_API_KEY
  if (!apiKey) {
    throw new Error('[PlanEmail] RESEND_API_KEY is not configured')
  }

  const resend = new Resend(apiKey)
  // Use onboarding@resend.dev until domain is verified in Resend
  const from = process.env.PLAN_EMAIL_FROM || 'ALE Digital Advisor <onboarding@resend.dev>'
  console.log('[PlanEmail] Sending from:', from, '| to:', email)
  const subject = SUBJECTS[locale] || SUBJECTS.en
  const dateStr = new Date().toISOString().slice(0, 10)

  const { data, error } = await resend.emails.send({
    from,
    to: [email],
    subject,
    html: buildHtmlBody(plan, email, locale),
    attachments: [
      {
        filename: `ALE-Plan-${dateStr}.pdf`,
        content: Buffer.from(pdfBytes).toString('base64'),
        contentType: 'application/pdf',
      },
    ],
  })

  if (error) {
    throw new Error(`[PlanEmail] Resend error: ${error.message}`)
  }

  console.log(`[PlanEmail] Email sent to ${email}, id: ${data?.id}`)
  return { id: data?.id || '' }
}
